### ISSUE TITLE
typo? client -> server

### ISSUE THREAD

**Issue by ahdinosaur** [staltz/ppppp-hub#2]
https://github.com/staltz/ppppp-hub/blob/ef89d8de8f52740b484d7713d6637495501555cc/lib/plugin-hub-client.cjs#L23C45-L23C45

i see this is the same as in https://github.com/staltz/ppppp-hub-client/blob/master/lib/plugin-hub.js, so i wonder if a typo.

**Comment by staltz** [comment]
Not a typo, but an unfortunate use of muxrpc where we need to implement the API in case we want to **call** the API remotely. The hub has to call `remotePeer.hubClient.connect` so that's why the hub implements a stub of hubClient.

**Comment by ahdinosaur** [comment]
okay!

by typo i was referring to the text in `ppppp-hub`: "Not implemented on the client". i thought that should say "Not implemented on the server". since the stub is on the server. similar to how the stub in `ppppp-client` also says "Not implemented on the client".

**Comment by staltz** [comment]
Didn't notice that, thanks! Fixed!
